theme: jekyll-theme-cayman

title: Pupil
description: Hitomi.la viewer for Android
baseurl: "/Pupil"

show_downloads: true
google_analytics: UA-119938781-2

github:
  app_url: https://github.com/tom5079/Pupil-issue/releases/download/1.1/Pupil-v1.1.apk
  issue_url: https://github.com/tom5079/Pupil-issue/issues/new/choose