theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap

title: Pupil
description: Hitomi.la viewer for Android
baseurl: "/Pupil"

google_analytics: UA-119938781-2

disqus_url: "https://pupil.disqus.com"
discord_url: "https://discord.gg/Stj4b5v"

github:
  latest_url: "https://github.com/tom5079/Pupil/releases/download/4.1/Pupil-v4.1.apk"
  release_url: "https://github.com/tom5079/Pupil/releases/"
  issue_url: "https://github.com/tom5079/Pupil/issues/"

t:
  en:
    header: 
      description: "Hitomi.la viewer for Android"
      download: "Download app"
      issue: "Having a problem?"
      or: "or…"
      email: "Send an E-mail"
      discord: "Join Discord server"
  ko:
    header:
      description: "안드로이드 Hitomi.la 뷰어"
      download: "앱 다운로드"
      issue: "문제가 있으세요?"
      or: "또는…"
      email: "이메일 보내기"
      discord: "디스코드"
