# Setup
title:        Pupil
tagline:      Hitomi.la viewer for Android
baseurl:      "/Pupil"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       tom5079
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown